### ISSUE TITLE
Rate values intermittently go to a huge value (1.845582e18) [LCLSPC-41]

### ISSUE THREAD

**Issue by klauer** [slac-epics/ca-gateway#1]
This _may_ apply to the upstream code and not just SLAC's. I haven't investigated, but am noting it here for future purposes.

![image](https://user-images.githubusercontent.com/5139267/102281042-0fe38780-3ee3-11eb-8f07-482bec628aac.png)

Just a guess, but looks like the ULONG->double calculation math may have some issues on when `a < b`, producing a negative rate which is mistakenly cast to something near ULONG_MAX:

https://github.com/slac-epics/ca-gateway/blob/72120c6512e040030c33467200824d6908eb29f1/src/gateServer.cc#L2168

https://github.com/slac-epics/ca-gateway/blob/72120c6512e040030c33467200824d6908eb29f1/src/gateServer.cc#L81

Also curious as to the benefit of doing 2's complement subtraction yourself instead of relying on `double`...

**Comment by bhill-slac** [comment]
The problem w/ doing the diff as a double is that double only has 52 bits of resolution and the values being diff'ed have 64 bits.

**Comment by bhill-slac** [comment]
The ULONG_DIFF macro looks right.   I added some test code and printf's to my gateway build and verified it rolls over ok.

**Comment by bhill-slac** [comment]
Looks like it's not the clientEventRate that does that, just serverEventRate and serverPostRate.    They're both defined as "unsigned" in the pcas module so they're rolling over on 32bits, not 64bits.    I'll put out a new version of pcas to fix this.

**Comment by bhill-slac** [comment]
This bug is fixed in pcas/R4.13.2-0.3.0 and is part of the new gateway/R2.1.2.0-1.4.0 release.

**Comment by bhill-slac** [comment]
This bug is fixed in pcas/R4.13.2-0.3.0 and is part of the new gateway/R2.1.2.0-1.4.0 release.
